spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db
    username: root
    password: nicathes
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update